#ifndef WORKER_EVS_H_
#define WORKER_EVS_H_
 
#define WORKER_INT_MAILIST(X) \
   X(WORKER_INT_SHUTDOWN_MID,             "MAILS TO SHUTDOWN WORKER") \

#define WORKER_PBC_MAILIST(X) \

#endif /*WORKER_EVS_H_*/
