#ifndef IPCGTESTWORKER_MAILIST_H_
#define IPCGTESTWORKER_MAILIST_H_
 
#define IPC_GTEST_INT_MAILIST(X) \
   X(IPC_GTEST_INT_MID,             "GTEST IPC INTERNAL") \

#define IPC_GTEST_PBC_MAILIST(X) \
   X(IPC_GTEST_PBC_MID, "MAILS TO ANY SUBSCRIBABLE") \

#endif /*IPCGTESTWORKER_MAILIST_H_*/
